apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-2
  template:
    metadata:
      labels:
        app: project-2
    spec:
      containers:
       - name: project-2
         image: adrian0186/testpro:latest
         imagePullPolicy: Always
         ports:
          - containerPort: 80



     